name: Build

on:
  push:
    branches:
      - 'trunk'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Gradle
        run: ./gradlew build

      - name: Increment the version code of your project
        uses: chkfung/android-version-actions@v1.1

